/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomnamepicker;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author computer
 */
public class Config extends javax.swing.JFrame {

    File file;
    int[] columnNumbers;
    String csvSplitter;
    boolean isFirstLineSkip;
    /**
     * Creates new form Ayarlar
     */
    public Config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jButtonFileChooser = new javax.swing.JButton();
        jLabelFileChooser = new javax.swing.JLabel();
        jLabelColumnNumber = new javax.swing.JLabel();
        jTextFieldColumnNumber = new javax.swing.JTextField();
        jLabelCSVSplitter = new javax.swing.JLabel();
        CSVSplitter = new javax.swing.JTextField();
        jLabelSkipFirtsLine = new javax.swing.JLabel();
        jComboBoxSkipFirstLine = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFileChooser.setText("Dosya Seç");

        jLabelFileChooser.setText("CSV Dosyası");

        jLabelColumnNumber.setText("Kolon Numaraları");

        jTextFieldColumnNumber.setText("2,14,15");

        jLabelCSVSplitter.setText("CSV Ayıracı");

        CSVSplitter.setText(",");

        jLabelSkipFirtsLine.setText("İlk Satır Olacak Mı?");

        jComboBoxSkipFirstLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EVET", "HAYIR" }));

        jButtonSave.setText("KAYDET");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSkipFirtsLine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSkipFirstLine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldColumnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelColumnNumber)
                                        .addComponent(jLabelFileChooser)
                                        .addComponent(jLabelCSVSplitter))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(CSVSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonFileChooser))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFileChooser)
                    .addComponent(jButtonFileChooser, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColumnNumber)
                    .addComponent(jTextFieldColumnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCSVSplitter)
                    .addComponent(CSVSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSkipFirtsLine)
                    .addComponent(jComboBoxSkipFirstLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public int[] getColumnNumbers() {
        return columnNumbers;
    }

    public void setColumnNumbers(int[] columnNumbers) {
        this.columnNumbers = columnNumbers;
    }

    public String getCsvSplitter() {
        return csvSplitter;
    }

    public void setCsvSplitter(String csvSplitter) {
        this.csvSplitter = csvSplitter;
    }

    public boolean isIsFirstLineSkip() {
        return isFirstLineSkip;
    }

    public void setIsFirstLineSkip(boolean isFirstLineSkip) {
        this.isFirstLineSkip = isFirstLineSkip;
    }

    public JTextField getCSVSplitter() {
        return CSVSplitter;
    }

    public void setCSVSplitter(JTextField CSVSplitter) {
        this.CSVSplitter = CSVSplitter;
    }

    
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
                
        String[] numbers = jTextFieldColumnNumber.getText().split(",");
       
        this.columnNumbers = new int[numbers.length];
        
        for (int i = 0; i < numbers.length; i++) {
            
            this.columnNumbers[i] =  (Integer)Integer.parseInt(numbers[i]);
        }
        
        this.csvSplitter = jLabelCSVSplitter.getText();
        
        
        if(jComboBoxSkipFirstLine.getSelectedIndex() == 0){
            this.isFirstLineSkip = true;
        }else {
            this.isFirstLineSkip = false;
        }
        // super.dispose() ;
        setVisible(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CSVSplitter;
    private javax.swing.JButton jButtonFileChooser;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxSkipFirstLine;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabelCSVSplitter;
    private javax.swing.JLabel jLabelColumnNumber;
    private javax.swing.JLabel jLabelFileChooser;
    private javax.swing.JLabel jLabelSkipFirtsLine;
    private javax.swing.JTextField jTextFieldColumnNumber;
    // End of variables declaration//GEN-END:variables
}
