/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomnamepicker;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 *
 * @author computer
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainFrame() {
        initComponents();

        CSVReader csvFileConverter  = new CSVReader("orders.csv");
        
        int[] columnNumbers         = new int[]{2, 14, 15};
        csvFileConverter.setColumnNumbers(columnNumbers);
        
        
        this.names = csvFileConverter.getNameList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabelResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSec = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gebze Teknik Üniversitesi Bilgisayar Mühendisliği Bölümü Geekday 2017 Kura");

        jLabelResult.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResult.setText("GEEKDAY 2017");
        jLabelResult.setAlignmentY(0.0F);
        jLabelResult.setFocusable(false);
        jLabelResult.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelResult.setIconTextGap(0);
        jLabelResult.setInheritsPopupMenu(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomnamepicker/geekday.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);

        jButtonSec.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSec.setText("SEÇ");
        jButtonSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Ayarlar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu.add(jMenu1);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(jButtonSec, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonSec, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecActionPerformed
        doWork();
    }//GEN-LAST:event_jButtonSecActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       // Config config = new Config();
       //  config.setVisible(true);
        
        // Set file and get names
//        CSVReader csvFileConverter  = new CSVReader(config.getFile().toString());
        
  //      int[] columnNumbers         = new int[]{2, 14, 15};
    //    csvFileConverter.setColumnNumbers(columnNumbers);
        
        
      //  this.names = csvFileConverter.getNameList();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.pack();
                frame.setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSec;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private List<String> names = new ArrayList<String>();
    
    private void doWork() {
        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
            
            int randomIndex;
            String winner = "";
            @Override
            protected Void doInBackground() throws Exception {
                
        
        
                long currrentTime   = System.currentTimeMillis();
                long waitTime       = currrentTime+3000;

                while(System.currentTimeMillis() < waitTime){

                    // Shuffle list
                    long seed = System.nanoTime();
                    Collections.shuffle(names, new Random(seed));
                
                    randomIndex = (int) (Math.random()*names.size());
                    Thread.sleep(10);
                    publish(randomIndex);
                    // System.out.print("randomIndex "+Integer.toString(randomIndex)+"\t");
                }
                
                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {
                
                winner = names.get(randomIndex);
                jLabelResult.setText(winner);
                
            }

            @Override
            protected void done() {
                jLabelResult.setText(winner);
                
                // Remove from list
                names.remove(randomIndex);
            }
        };
        worker.execute();
    }
}
